project_id = "glxupcdgtzqkaxcgezeu"

[functions.gita-coach]
verify_jwt = false

[functions.search-shloks]
verify_jwt = false

[functions.admin-ai-generate]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false

[functions.admin-crud]
verify_jwt = false

[functions.google-tts]
verify_jwt = false

[functions.translate-message]
verify_jwt = false

[functions.test-api-connection]
verify_jwt = false